# Generated by Django 3.2.5 on 2021-07-05 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20210705_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
